import './styles.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { cookies } from 'next/headers'
import { AppSidebar } from '@/components/app-sidebar'
import { ChatSidebar } from '@/components/chat-sidebar'
import { DynamicBreadcrumb } from '@/components/dynamic-breadcrumb'
import { Separator } from '@/components/ui/separator'
import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import {
  SidebarInset as SidebarInsetChat,
  SidebarProvider as SidebarProviderChat,
  SidebarTrigger as SidebarTriggerChat,
} from '@/components/ui/sidebar-chat'

import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { FavoritesProvider } from '@/contexts/favorites-context'

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get('sidebar_state')?.value === 'true'
  const defaultChatOpen = cookieStore.get('sidebar_chat_state')?.value === 'true'

  return (
    <html lang="en">
      <body>
        <div>
          <FavoritesProvider>
            <TooltipProvider>
              <SidebarProvider defaultOpen={defaultOpen}>
                <AppSidebar id="left" />
                <SidebarProviderChat defaultOpen={defaultChatOpen}>
                  <SidebarInset>
                  <header className="bg-background sticky top-0 flex h-16 shrink-0 items-center gap-2 border-b px-4">
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <SidebarTrigger className="-ml-1" />
                      </TooltipTrigger>
                      <TooltipContent>
                        <p>Expand/collapse sidebar (⌘B)</p>
                      </TooltipContent>
                    </Tooltip>
                    <Separator orientation="vertical" className="mr-2 h-4" />
                    <DynamicBreadcrumb />
                    <div className="flex-1" />
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <SidebarTriggerChat />
                      </TooltipTrigger>
                      <TooltipContent>
                        <p>Expand/collapse AI chat (⌘M)</p>
                      </TooltipContent>
                    </Tooltip>
                  </header>
                  <div className="flex flex-1 flex-col gap-4 p-4">
                    {children}
                    {/* {Array.from({ length: 24 }).map((_, index) => (
                    <div key={index} className="bg-muted/50 aspect-video h-12 w-full rounded-lg" />
                  ))} */}
                  </div>
                </SidebarInset>

                  <ChatSidebar side="right" />
                </SidebarProviderChat>
              </SidebarProvider>
            </TooltipProvider>
          </FavoritesProvider>
        </div>
      </body>
    </html>
  )
}
