import './styles.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { AppSidebar } from '@/components/app-sidebar'
import { ChatSidebar } from '@/components/chat-sidebar'
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@/components/ui/breadcrumb'
import { Separator } from '@/components/ui/separator'
import { SidebarInset, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import {
  SidebarInset as SidebarInsetChat,
  SidebarProvider as SidebarProviderChat,
  SidebarTrigger as SidebarTriggerChat,
} from '@/components/ui/sidebar-chat'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div>
          <SidebarProvider>
            <SidebarProviderChat>
              <AppSidebar id="left" />
              <SidebarInset>
                <header className="bg-background sticky top-0 flex h-16 shrink-0 items-center gap-2 border-b px-4">
                  <SidebarTrigger className="-ml-1" />
                  <Separator orientation="vertical" className="mr-2 h-4" />
                  <Breadcrumb>
                    <BreadcrumbList>
                      <BreadcrumbItem className="hidden md:block">
                        <BreadcrumbLink href="#">Building Your Application</BreadcrumbLink>
                      </BreadcrumbItem>
                      <BreadcrumbSeparator className="hidden md:block" />
                      <BreadcrumbItem>
                        <BreadcrumbPage>Data Fetching</BreadcrumbPage>
                      </BreadcrumbItem>
                    </BreadcrumbList>
                  </Breadcrumb>
                  <div className="flex-1" />
                  <SidebarTriggerChat />
                </header>
                <div className="flex flex-1 flex-col gap-4 p-4">
                  {children}
                  {Array.from({ length: 24 }).map((_, index) => (
                    <div key={index} className="bg-muted/50 aspect-video h-12 w-full rounded-lg" />
                  ))}
                </div>
              </SidebarInset>
              <ChatSidebar side="right" collapsible="icon" />
            </SidebarProviderChat>
          </SidebarProvider>
        </div>
      </body>
    </html>
  )
}
