# Jekyll configuration for GitHub Pages
title: Kunskapsportal
description: AI-driven kunskapsdatabas för svensk kommunal förvaltning
baseurl: "/kunskapsportal"
url: "https://falkenbergs-kommun.github.io"

# No theme - using custom layout
# theme: jekyll-theme-cayman

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings

# Relative links
relative_links:
  enabled: true
  collections: true

# Optional front matter
optional_front_matter:
  remove_originals: false

# Titles from headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Exclude from processing
exclude:
  - node_modules
  - vendor
  - README.md
  - package.json
  - pnpm-lock.yaml
  - tsconfig.json
