export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { FavoritesProvider } from '@/contexts/favorites-context'
import '../globals.css'
import '../../app/(frontend)/styles.css'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;800&family=Lato:wght@300;400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-gray-50 p-8 prose prose-slate max-w-none">
        <FavoritesProvider>{children}</FavoritesProvider>
      </body>
    </html>
  )
}
