export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { FavoritesProvider } from '@/contexts/favorites-context'
import '../globals.css'
import '../../app/(frontend)/styles.css'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <FavoritesProvider>{children}</FavoritesProvider>
      </body>
    </html>
  )
}
